[package]
name = "xtask"
version = "0.1.0"
authors = ["Jialun Cai <jialun.cai@pm.me>"]
edition = "2024"

[dependencies]
anyhow = "1"
console = "0.15"
clap = { version = "4", features = ["derive"] }
duct = "0.13"
